TeleCall uses 4 centers around the globe to process customer order forms.They audit a certain % of the customer order forms.
Any error in order form renders it defective and has to be reworked before processing.The manager wants to check whether the defective % varies by centre. Please analyze the data at 5% significance level and help the manager draw appropriate inferences.


In [26]:
import pandas as pd 
from scipy import stats

In [8]:
customerorderform_data=pd.read_csv("Costomer+OrderForm.csv")
customerorderform_data

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [11]:
customerorderform_data["Phillippines"].value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [12]:
customerorderform_data["Indonesia"].value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [14]:
customerorderform_data["Malta"].value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [15]:
customerorderform_data["India"].value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [16]:
obs=np.array([[271,267,269,280],[29,33,31,20]])
obs

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

Null Hypothesis Ho:customer order forms defective % does not varies by center.
Alternate Hypothesis Ha:customer order forms defective % varies by center.

In [27]:
chi_square_score,pvalue,df,exp_table=stats.chi2_contingency(obs)
print('Chi-square score is {}.\npvalue is {}.\ndf is {}.\nExpected table is \n{}'.format(chi_square_score,pvalue,df,exp_table))

Chi-square score is 3.858960685820355.
pvalue is 0.2771020991233135.
df is 3.
Expected table is 
[[271.75 271.75 271.75 271.75]
 [ 28.25  28.25  28.25  28.25]]


Comparing pvalue with 5% significance level.Since pvalue>0.05,We do not reject the null hypothesis saying that the customer order forms defective % does not varies by center.